structures_avancees.elf : structures_avancees.c
		cc -Wall -o structures_avancees.elf structures_avancees.c

structures_avancees.exe : structures_avancees_w.c
		clang.exe -Wall -o structures_avancees.exe structures_avancees_w.c
