bottom_of_the_pit : bottom_of_the_pit.s
	as -a bottom_of_the_pit.s -o bottom_of_the_pit.o > bottom_of_the_pit_comment.o
	ld -e main bottom_of_the_pit.o -o bottom_of_the_pit.elf
	rm bottom_of_the_pit.o
