librairie_standard.elf: librairie_standard.c
		cc -Wall -o librairie_standard.elf librairie_standard.c

librairie_standard.exe: librairie_standard_w.c
		clang.exe -Wall -o librairie_standard.exe librairie_standard_w.c
